# playbook-resolv.yml
---
-
    name: 'Add name server entry if not already entered'
    hosts: localhost
    tasks:
        -
            shell: 'cat /etc/resolv.conf'
            # solution 1
            register: command_output
        -
            shell: 'echo "nameserver 10.0.250.10" >> /etc/resolv.conf'
            # solution 2
            when: 'command_output.stdout.find("10.0.250.10") == -1'
